using System.Net.Http.Headers;
using System.Text;
using System.Text.Json;

namespace whatsapp_tests.Services
{
    public class WhatsAppServiceMainMenuCFE
    {
        private readonly HttpClient _httpClient;

        // constructor
        
        public WhatsAppServiceMainMenuCFE(HttpClient httpClient, String WhatsAppToken)
        {
            _httpClient = httpClient;
            _httpClient.DefaultRequestHeaders.Authorization =
                new AuthenticationHeaderValue(
                    "Bearer",
                    WhatsAppToken
            );
        }
        

        public WhatsAppServiceMainMenuCFE(HttpClient httpClient)
        {
            _httpClient = httpClient;
            _httpClient.DefaultRequestHeaders.Authorization =
                new AuthenticationHeaderValue(
                    "Bearer",
                    "EAATyUT8goNsBO78PyQq3tlsaWnzbTixRjgmt3BXMTyLjMMbj2TZCuMLBaO6IcACTg378MBthV6S1dBDWIUd66nY2nVq3ZBexXWGUGYLWBqh7h7T9UZAlSj5BveosOVi7vv02YiaBQReeh5IckMazdPR4f85ZCOzXcEkmCZB64ozUgFcOr5TRvdZCKJ1etF1kQpVqiHoLopqXKBLBjZCjNZBtiWe9ebqxMeR9crJVRR3zYbQZD"
                );
        }

        // this method encapsulates the cURL Http request
        // generated by whatsapp's API 
        // 'toPhoneNumber' is the phone # of the client
        // who is requesting the bot's features
        public async Task SendMainMenuAsync(string toPhoneNumber)
        {
            // this entire thing is what would go inside one of those
            // huge JSON packages that whatsapp API generates
            var jsonBody = new
            {
                messaging_product = "whatsapp",
                recipient_type = "individual",
                to = toPhoneNumber,
                type = "interactive",
                // this is the JSON block 
                // where the menu and its contents are displayed
                interactive = new
                {
                    type = "list",
                    // header
                    header = new
                    {
                        type = "text",
                        text = "Gracias por contactar a la CFE."
                    },
                    // body
                    body = new
                    {
                        text = "Haga click en en menu de opciones para elegir su consulta."
                    },
                    // action: options the whatsapp bot displays for the user
                    // to select with simple numerical commands
                    action = new
                    {
                        button = "Menu de opciones",
                        sections = new[]
                        {
                            new
                            {
                                title = "Menu principal",
                                rows = new[]
                                {
                                    new { 
                                        id = "ROW_CLEAR_BAL", 
                                        title = "1", 
                                        description = "Para Conocer saldo a favor, responder con 1." 
                                    },
                                    new { 
                                        id = "ROW_OUT_BAL", 
                                        title = "2", 
                                        description = "Para Conocer saldo a pagar, responder con 2." 
                                    },
                                    new { 
                                        id = "ROW_DUE_DATE", 
                                        title = "3", 
                                        description = "Para conocer fecha limite; responder al bot con 3."
                                    },
                                    new { 
                                        id = "ROW_SUPPORT", 
                                        title = "4", 
                                        description = "Si ninguna opcion satisface, contactar soporte." 
                                    }
                                }// end of rows
                            }// end of new JSON/cURL block
                        }//end of sections
                    }//end of action
                }// end of interactive block
            };
            
            // these two lines of code encapsulate the aforementioned...
            var content = new StringContent(JsonSerializer.Serialize(jsonBody), Encoding.UTF8, "application/json");
            // and then send an asyncronous request, to the graph.facebook webhook, then wait for a response
            var response = await _httpClient.PostAsync("https://graph.facebook.com/v17.0/579992435207524/messages", content);

            response.EnsureSuccessStatusCode();
        }

    }// end of whatsappserviceMenuCFE class
}
